"""Tests for the markdown generator."""

from pathlib import Path
from repo_notes.generator import MarkdownGenerator
from repo_notes.extractors.structure import StructureResult
from repo_notes.extractors.key_files import KeyFilesResult
from repo_notes.extractors.stats import StatsResult
from repo_notes.extractors.git import GitResult
from repo_notes.extractors.architecture import ArchitectureResult
from repo_notes.extractors.security import SecurityResult
from repo_notes.extractors.dependencies import DependenciesResult


def test_generates_title():
    gen = MarkdownGenerator(Path("my-project"))
    md = gen.generate()
    assert md.startswith("# Repository Notes: my-project")
    assert "Generated by repo-notes" in md


def test_includes_structure():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        structure=StructureResult(tree="root/\n  main.py", file_count=1, dir_count=1)
    )
    assert "## Project Structure" in md
    assert "root/" in md
    assert "main.py" in md


def test_includes_key_files():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        key_files=KeyFilesResult(categories={"readme": [Path("README.md")]})
    )
    assert "## Key Files" in md
    assert "Readme" in md
    assert "README.md" in md


def test_includes_stats():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        stats=StatsResult(
            total_files=10,
            total_lines=500,
            total_size=2048,
            by_language={"python": {"files": 5, "lines": 300, "size": 1024}},
            largest_files=[(Path("main.py"), 200)],
        )
    )
    assert "## Code Statistics" in md
    assert "10" in md
    assert "500" in md
    assert "python" in md
    assert "200" in md


def test_includes_git():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        git=GitResult(
            is_repo=True,
            current_branch="main",
            recent_commits=[
                {"hash": "abc12345", "author": "Alice", "date": "2024-01-01", "message": "Initial commit"}
            ],
            branches=["main", "dev"],
            contributors=[{"name": "Alice", "commits": 10}],
            remote_url="https://github.com/user/repo.git",
        )
    )
    assert "## Git Information" in md
    assert "main" in md
    assert "Alice" in md


def test_includes_architecture():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        arch=ArchitectureResult(
            layers={"models": [Path("user.py"), Path("post.py")]},
            entry_points=[Path("main.py")],
        )
    )
    assert "## Architecture Overview" in md
    assert "Models" in md
    assert "main.py" in md


def test_includes_security():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        security=SecurityResult(
            findings=[{"file": "config.py", "type": "API Key", "line": 5, "preview": "sk-*****"}],
            env_files=[Path(".env")],
        )
    )
    assert "## Security Notes" in md
    assert ".env" in md
    assert "API Key" in md


def test_includes_dependencies():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        deps=DependenciesResult(
            python={"requirements.txt": ["flask", "requests"]},
        )
    )
    assert "## Dependencies" in md
    assert "Python" in md
    assert "requirements.txt" in md


def test_omits_git_when_not_repo():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        git=GitResult(is_repo=False)
    )
    assert "## Git Information" not in md


def test_omits_empty_sections():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate()
    assert "## " not in md  # No section headers