"""Tests for the markdown generator."""

from pathlib import Path
from unittest.mock import patch

from repo_notes.extractors import (
    ApiEndpointResult,
    ArchitectureResult,
    CicdResult,
    ComplexityResult,
    DatabaseResult,
    DependenciesResult,
    DuplicateResult,
    EnvVarsResult,
    GitResult,
    ScriptsResult,
    SecurityResult,
    StatsResult,
    StructureResult,
    TodosResult,
    TypeCoverageResult,
)
from repo_notes.generator import MarkdownGenerator


def test_generates_title():
    gen = MarkdownGenerator(Path("my-project"))
    md = gen.generate()
    assert md.startswith("# Repository Notes: my-project")
    assert "Generated by repo-notes" in md


def test_includes_structure():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        structure=StructureResult(tree="root/\n  main.py", file_count=1, dir_count=1)
    )
    assert "## Project Structure" in md
    assert "root/" in md
    assert "main.py" in md


def test_includes_project_intelligence():
    from repo_notes.extractors import ProjectIntelligenceResult
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        project_intelligence=ProjectIntelligenceResult(categories={"readme": [Path("README.md")]})
    )
    assert "## Project Intelligence" in md
    assert "Readme" in md
    assert "README.md" in md


def test_includes_stats():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        stats=StatsResult(
            total_files=10,
            total_lines=500,
            total_size=2048,
            by_language={"python": {"files": 5, "lines": 300, "size": 1024}},
            largest_files=[(Path("main.py"), 200)],
        )
    )
    assert "## Code Statistics" in md
    assert "10" in md
    assert "500" in md
    assert "python" in md
    assert "200" in md


def test_includes_git():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        git=GitResult(
            is_repo=True,
            current_branch="main",
            recent_commits=[
                {"hash": "abc12345", "author": "Alice", "date": "2024-01-01", "message": "Initial commit"}
            ],
            branches=["main", "dev"],
            contributors=[{"name": "Alice", "commits": 10}],
            remote_url="https://github.com/user/repo.git",
        )
    )
    assert "## Git Information" in md
    assert "main" in md
    assert "Alice" in md


def test_includes_architecture():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        arch=ArchitectureResult(
            layers={"models": [Path("user.py"), Path("post.py")]},
            entry_points=[Path("main.py")],
            import_graph={"user.py": ["models", "utils"], "main.py": ["user"]},
        )
    )
    assert "## Architecture Overview" in md
    assert "Models" in md
    assert "main.py" in md
    assert "Import Graph" in md
    assert "user.py" in md
    assert "models" in md


def test_architecture_compact_dependency_summary():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        arch=ArchitectureResult(
            layers={},
            entry_points=[],
            import_graph={"a.py": ["b"], "b.py": ["c"], "c.py": ["a"]},
            circular_deps=[["a.py", "b.py", "c.py", "a.py"]],
        )
    )
    assert "Module Dependencies" in md
    assert "**3** modules import **3** other modules" in md
    assert "**1** circular dependency detected" in md
    assert "a.py → b.py → c.py → a.py" in md


def test_architecture_coupling_hotspots_rendered():
    gen = MarkdownGenerator(Path("root"))
    from repo_notes.extractors.architecture import CouplingHotspot
    md = gen.generate(
        arch=ArchitectureResult(
            layers={},
            entry_points=[],
            import_graph={"hub.py": ["a", "b"], "a.py": ["b"]},
            coupling_hotspots=[
                CouplingHotspot(file="hub.py", outgoing=2, incoming=0, total=2),
                CouplingHotspot(file="a.py", outgoing=1, incoming=0, total=1),
            ],
        )
    )
    assert "High-Coupling Files" in md
    assert "hub.py" in md
    assert "2 connections" in md
    assert "0 incoming, 2 outgoing" in md or "2 outgoing, 0 incoming" in md


def test_architecture_dead_code_candidates_rendered():
    gen = MarkdownGenerator(Path("root"))
    from repo_notes.extractors.architecture import DeadCodeCandidate
    md = gen.generate(
        arch=ArchitectureResult(
            layers={},
            entry_points=[],
            import_graph={"a.py": ["b"]},
            dead_code_candidates=[
                DeadCodeCandidate(file="orphan.py", reason="no inbound local imports; no outbound local imports"),
            ],
        )
    )
    assert "Low-Reachability Candidates" in md
    assert "orphan.py" in md
    assert "no inbound local imports" in md


def test_architecture_missing_test_candidates_rendered():
    gen = MarkdownGenerator(Path("root"))
    from repo_notes.extractors.architecture import MissingTestCandidate
    md = gen.generate(
        arch=ArchitectureResult(
            import_graph={"a.py": ["b"]},
            missing_test_candidates=[
                MissingTestCandidate(file="orphan.py", reason="no matching direct test file found"),
            ],
        )
    )
    assert "Missing Direct Test Candidates" in md
    assert "orphan.py" in md
    assert "no matching direct test file found" in md


def test_architecture_missing_test_candidates_empty():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        arch=ArchitectureResult(import_graph={"a.py": ["b"]}),
    )
    assert "Missing Direct Test Candidates" not in md


def test_architecture_test_signals_count_rendered():
    gen = MarkdownGenerator(Path("root"))
    from repo_notes.extractors.architecture import TestSignal
    md = gen.generate(
        arch=ArchitectureResult(
            import_graph={"a.py": ["b"]},
            test_signals=[
                TestSignal(file="a.py", test_files=["test_a.py"]),
                TestSignal(file="b.py", test_files=["test_b.py"]),
            ],
        )
    )
    assert "**2** source files have likely direct test files" in md
    # Should not dump the full file list
    assert "test_a.py" not in md
    assert "test_b.py" not in md


def test_architecture_test_signals_count_empty():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        arch=ArchitectureResult(import_graph={"a.py": ["b"]}),
    )
    assert "source files have likely direct test files" not in md


def test_architecture_dead_code_candidates_empty():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        arch=ArchitectureResult(import_graph={"a.py": ["b"]}),
    )
    assert "Low-Reachability Candidates" not in md


def test_architecture_coupling_hotspots_empty():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        arch=ArchitectureResult(
            import_graph={"a.py": ["b"]},
        )
    )
    assert "High-Coupling Files" not in md


def test_architecture_no_circular_deps():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        arch=ArchitectureResult(
            layers={},
            entry_points=[],
            import_graph={"a.py": ["b"]},
        )
    )
    assert "Module Dependencies" in md
    assert "**1** module imports **1** other module" in md
    assert "circular" not in md


def test_includes_security():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        security=SecurityResult(
            findings=[{"file": "config.py", "type": "API Key", "line": 5, "preview": "sk-*****"}],
            env_files=[Path(".env")],
        )
    )
    assert "## Security Notes" in md
    assert ".env" in md
    assert "API Key" in md


def test_includes_dependencies():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        deps=DependenciesResult(
            python={"requirements.txt": ["flask", "requests"]},
        )
    )
    assert "## Dependencies" in md
    assert "Python" in md
    assert "requirements.txt" in md


def test_omits_git_when_not_repo():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        git=GitResult(is_repo=False)
    )
    assert "## Git Information" not in md


def test_omits_empty_sections():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate()
    assert "## " not in md


def test_includes_todos():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        todos=TodosResult(
            items=[
                {"tag": "FIXME", "file": "main.py", "line": 10, "message": "fix this"},
                {"tag": "TODO", "file": "utils.py", "line": 5, "message": "add docstring"},
            ],
            count_by_tag={"FIXME": 1, "TODO": 1},
        )
    )
    assert "TODO / FIXME / HACK" in md
    assert "FIXME" in md
    assert "main.py" in md
    assert "fix this" in md


def test_includes_scripts():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        scripts=ScriptsResult(
            package_json={"test": "vitest run", "build": "vite build"},
            makefile_targets=["clean", "all"],
            justfile_recipes=["lint", "fmt"],
            pyproject_scripts={"dev": "uvicorn app:main"},
        )
    )
    assert "Build Scripts" in md
    assert "vitest run" in md
    assert "clean" in md
    assert "lint" in md
    assert "uvicorn" in md


def test_includes_env_vars():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        env_vars=EnvVarsResult(
            variables={"DATABASE_URL": ["config.py", ".env.example"], "API_KEY": ["config.py"]}
        )
    )
    assert "Environment Variables" in md
    assert "DATABASE_URL" in md
    assert "API_KEY" in md
    assert "config.py" in md


def test_includes_cicd():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        cicd=CicdResult(
            github_actions=[{"name": "CI", "on": ["push", "pull_request"], "jobs": ["test", "lint"]}],
            gitlab_ci=[{"name": "build", "stage": "build", "image": "python:3.12"}],
            circleci=[{"name": "test", "steps": 3}],
            jenkins_stages=["Build", "Test"],
        )
    )
    assert "CI/CD Configuration" in md
    assert "GitHub Actions" in md
    assert "CI" in md
    assert "push" in md
    assert "GitLab CI" in md
    assert "CircleCI" in md
    assert "Jenkins" in md


def test_includes_database():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        database=DatabaseResult(
            migration_files=[Path("migrations/001_init.py")],
            model_files=[Path("models/user.py"), Path("models/post.py")],
            model_count=2,
            schema_files=[Path("schema.sql")],
            orm_types=["SQLAlchemy"],
        )
    )
    assert "Database Schema" in md
    assert "Migration Files" in md
    assert "001_init" in md
    assert "models/user.py" in md
    assert "schema.sql" in md
    assert "SQLAlchemy" in md


def test_includes_type_coverage():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        type_coverage=TypeCoverageResult(
            typed_files=5,
            untyped_files=3,
            typed_lines=200,
            untyped_lines=100,
            by_extension={".py": {"files": 8, "typed_lines": 200, "untyped_lines": 100}},
        )
    )
    assert "Type Coverage" in md
    assert "62.5%" in md  # 5/8 * 100
    assert "5 typed files" in md
    assert "200" in md
    assert ".py" in md


def test_includes_complexity():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        complexity=ComplexityResult(
            complex_files=[{"file": "main.py", "long_functions": ["foo", "bar"], "max_nesting": 5, "score": 50}],
            avg_function_length=15.5,
            max_nesting=5,
        )
    )
    assert "Code Complexity" in md
    assert "Average function length" in md
    assert "15.5" in md
    assert "Complex Files" in md
    assert "main.py" in md


def test_includes_duplicates():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        duplicates=DuplicateResult(
            duplicates=[{"file": "copy.py", "duplicate_of": "original.py", "size": 100, "similarity": 0.95}],
            total_duplicates=1,
            total_saved_bytes=80,
        )
    )
    assert "Duplicate Files" in md
    assert "found" in md
    assert "80.0" in md
    assert "copy.py" in md
    assert "original.py" in md
    assert "95%" in md


def test_includes_api_endpoints():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        api_endpoints=ApiEndpointResult(
            endpoints=[
                {"framework": "FastAPI", "method": "GET", "path": "/items", "file": "main.py", "line": 10},
                {"framework": "Flask", "method": "POST", "path": "/users", "file": "app.py", "line": 5},
            ]
        )
    )
    assert "API Endpoints" in md
    assert "FastAPI" in md
    assert "Flask" in md
    assert "/items" in md
    assert "/users" in md


# Badge tests

def test_badges_show_stats():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        stats=StatsResult(
            total_files=10,
            total_lines=500,
            total_size=2048,
            by_language={"python": {"files": 5, "lines": 300, "size": 1024}},
            largest_files=[],
        )
    )
    assert "**10** files" in md
    assert "**500** lines" in md
    assert "**1** languages" in md


def test_badges_show_security_high():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        security=SecurityResult(
            findings=[{"file": "x.py", "type": "Key", "line": 1, "preview": "sk-****"}],
            env_files=[],
        ),
        stats=StatsResult(total_files=1, total_lines=10, total_size=100, by_language={}, largest_files=[]),
    )
    assert "**1** high" in md


def test_badges_show_security_mild():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        security=SecurityResult(
            findings=[],
            high_entropy_strings=[{"file": "x.py", "entropy": 4.5, "line": 1, "preview": "abc"}],
            env_files=[],
        ),
        stats=StatsResult(total_files=1, total_lines=10, total_size=100, by_language={}, largest_files=[]),
    )
    assert "**1** mild" in md


def test_badges_show_git():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        git=GitResult(
            is_repo=True,
            current_branch="main",
            recent_commits=[{"hash": "a", "author": "x", "date": "d", "message": "m"}],
            branches=[],
            contributors=[],
            remote_url="",
        ),
        stats=StatsResult(total_files=1, total_lines=10, total_size=100, by_language={}, largest_files=[]),
    )
    assert "branch **main**" in md


def test_badges_omitted_when_no_data():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate()
    # No badges should appear when nothing is passed
    assert "files" not in md or "**0** files" not in md  # no stats data


# Collapsible tests

def test_stats_table_collapsed():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        stats=StatsResult(
            total_files=5,
            total_lines=100,
            total_size=500,
            by_language={"python": {"files": 3, "lines": 60, "size": 300}},
            largest_files=[(Path("main.py"), 50)],
        )
    )
    assert "<details>" in md
    assert "<summary>By Language" in md
    assert "<summary>Largest Files" in md


def test_security_findings_open():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        security=SecurityResult(
            findings=[{"file": "x.py", "type": "Key", "line": 1, "preview": "sk-****"}],
            env_files=[],
        )
    )
    assert "<details open>" in md
    assert "<summary>Potential Secrets" in md


def test_security_high_entropy_collapsed():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        security=SecurityResult(
            findings=[],
            high_entropy_strings=[{"file": "x.py", "entropy": 4.5, "line": 1, "preview": "abcdef123456"}],
            env_files=[],
        )
    )
    assert "<details>" in md
    assert "<summary>High Entropy Strings" in md
    assert "<details open>" not in md


def test_structure_not_collapsed():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        structure=StructureResult(tree="root/", file_count=1, dir_count=0)
    )
    assert "<details>" not in md


# Section ordering tests

def test_section_order():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        structure=StructureResult(tree="root/", file_count=1, dir_count=0),
        stats=StatsResult(total_files=1, total_lines=10, total_size=100, by_language={}, largest_files=[]),
        section_order=["stats", "structure"],
    )
    # Code Statistics should appear before Project Structure
    assert md.index("## Code Statistics") < md.index("## Project Structure")


def test_section_order_default():
    gen = MarkdownGenerator(Path("root"))
    md_default = gen.generate(
        structure=StructureResult(tree="root/", file_count=1, dir_count=0),
        stats=StatsResult(total_files=1, total_lines=10, total_size=100, by_language={}, largest_files=[]),
    )
    md_ordered = gen.generate(
        structure=StructureResult(tree="root/", file_count=1, dir_count=0),
        stats=StatsResult(total_files=1, total_lines=10, total_size=100, by_language={}, largest_files=[]),
        section_order=None,
    )
    # Both should have same structure
    assert "## Project Structure" in md_default
    assert "## Code Statistics" in md_ordered


def test_section_order_skips_missing():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        stats=StatsResult(total_files=1, total_lines=10, total_size=100, by_language={}, largest_files=[]),
        section_order=["structure", "stats"],
    )
    # structure is in order but not passed, so only stats appears
    assert "## Code Statistics" in md
    assert "## Project Structure" not in md


# Snapshot tests — stable, reviewable full-output checks

def test_markdown_snapshot_matches():
    """Full MarkdownGenerator output with consistent inputs."""
    with patch("repo_notes.generator.__version__", "0.0.0"):
        gen = MarkdownGenerator(Path("test-project"))
        md = gen.generate(
            structure=StructureResult(
                tree="test-project/\n  src/\n    main.py",
                file_count=1, dir_count=1,
            ),
            stats=StatsResult(
                total_files=1, total_lines=10, total_size=100,
                by_language={"Python": {"files": 1, "lines": 10, "size": 100}},
                largest_files=[],
            ),
        )
    assert md == (
        "# Repository Notes: test-project\n"
        "\n"
        "*Generated by repo-notes v0.0.0*\n"
        "\n"
        "**1** files · **10** lines · 100.0 B · **1** languages\n"
        "\n"
        "## Project Structure\n"
        "\n"
        "```text\n"
        "test-project/\n"
        "  src/\n"
        "    main.py\n"
        "```\n"
        "\n"
        "*1 files, 1 directories*\n"
        "\n"
        "## Code Statistics\n"
        "\n"
        "- **Total files**: 1\n"
        "- **Total lines**: 10\n"
        "- **Total size**: 100.0 B\n"
        "\n"
        "<details>\n"
        "<summary>By Language (1 languages)</summary>\n"
        "\n"
        "### By Language\n"
        "\n"
        "| Language | Files | Lines | Size |\n"
        "|----------|-------|-------|------|\n"
        "| Python | 1 | 10 | 100.0 B |\n"
        "\n"
        "\n"
        "</details>\n"
    )
