"""Tests for the markdown generator."""

from pathlib import Path
from repo_notes.generator import MarkdownGenerator
from repo_notes.extractors.structure import StructureResult
from repo_notes.extractors.key_files import KeyFilesResult
from repo_notes.extractors.stats import StatsResult
from repo_notes.extractors.git import GitResult
from repo_notes.extractors.architecture import ArchitectureResult
from repo_notes.extractors.security import SecurityResult
from repo_notes.extractors.dependencies import DependenciesResult


def test_generates_title():
    gen = MarkdownGenerator(Path("my-project"))
    md = gen.generate()
    assert md.startswith("# Repository Notes: my-project")
    assert "Generated by repo-notes" in md


def test_includes_structure():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        structure=StructureResult(tree="root/\n  main.py", file_count=1, dir_count=1)
    )
    assert "## Project Structure" in md
    assert "root/" in md
    assert "main.py" in md


def test_includes_key_files():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        key_files=KeyFilesResult(categories={"readme": [Path("README.md")]})
    )
    assert "## Key Files" in md
    assert "Readme" in md
    assert "README.md" in md


def test_includes_stats():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        stats=StatsResult(
            total_files=10,
            total_lines=500,
            total_size=2048,
            by_language={"python": {"files": 5, "lines": 300, "size": 1024}},
            largest_files=[(Path("main.py"), 200)],
        )
    )
    assert "## Code Statistics" in md
    assert "10" in md
    assert "500" in md
    assert "python" in md
    assert "200" in md


def test_includes_git():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        git=GitResult(
            is_repo=True,
            current_branch="main",
            recent_commits=[
                {"hash": "abc12345", "author": "Alice", "date": "2024-01-01", "message": "Initial commit"}
            ],
            branches=["main", "dev"],
            contributors=[{"name": "Alice", "commits": 10}],
            remote_url="https://github.com/user/repo.git",
        )
    )
    assert "## Git Information" in md
    assert "main" in md
    assert "Alice" in md


def test_includes_architecture():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        arch=ArchitectureResult(
            layers={"models": [Path("user.py"), Path("post.py")]},
            entry_points=[Path("main.py")],
        )
    )
    assert "## Architecture Overview" in md
    assert "Models" in md
    assert "main.py" in md


def test_includes_security():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        security=SecurityResult(
            findings=[{"file": "config.py", "type": "API Key", "line": 5, "preview": "sk-*****"}],
            env_files=[Path(".env")],
        )
    )
    assert "## Security Notes" in md
    assert ".env" in md
    assert "API Key" in md


def test_includes_dependencies():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        deps=DependenciesResult(
            python={"requirements.txt": ["flask", "requests"]},
        )
    )
    assert "## Dependencies" in md
    assert "Python" in md
    assert "requirements.txt" in md


def test_omits_git_when_not_repo():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        git=GitResult(is_repo=False)
    )
    assert "## Git Information" not in md


def test_omits_empty_sections():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate()
    assert "## " not in md


# Badge tests

def test_badges_show_stats():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        stats=StatsResult(
            total_files=10,
            total_lines=500,
            total_size=2048,
            by_language={"python": {"files": 5, "lines": 300, "size": 1024}},
            largest_files=[],
        )
    )
    assert "**10** files" in md
    assert "**500** lines" in md
    assert "**1** languages" in md


def test_badges_show_security_high():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        security=SecurityResult(
            findings=[{"file": "x.py", "type": "Key", "line": 1, "preview": "sk-****"}],
            env_files=[],
        ),
        stats=StatsResult(total_files=1, total_lines=10, total_size=100, by_language={}, largest_files=[]),
    )
    assert "**1** high" in md


def test_badges_show_security_mild():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        security=SecurityResult(
            findings=[],
            high_entropy_strings=[{"file": "x.py", "entropy": 4.5, "line": 1, "preview": "abc"}],
            env_files=[],
        ),
        stats=StatsResult(total_files=1, total_lines=10, total_size=100, by_language={}, largest_files=[]),
    )
    assert "**1** mild" in md


def test_badges_show_git():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        git=GitResult(
            is_repo=True,
            current_branch="main",
            recent_commits=[{"hash": "a", "author": "x", "date": "d", "message": "m"}],
            branches=[],
            contributors=[],
            remote_url="",
        ),
        stats=StatsResult(total_files=1, total_lines=10, total_size=100, by_language={}, largest_files=[]),
    )
    assert "branch **main**" in md


def test_badges_omitted_when_no_data():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate()
    # No badges should appear when nothing is passed
    assert "files" not in md or "**0** files" not in md  # no stats data


# Collapsible tests

def test_stats_table_collapsed():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        stats=StatsResult(
            total_files=5,
            total_lines=100,
            total_size=500,
            by_language={"python": {"files": 3, "lines": 60, "size": 300}},
            largest_files=[(Path("main.py"), 50)],
        )
    )
    assert "<details>" in md
    assert "<summary>By Language" in md
    assert "<summary>Largest Files" in md


def test_security_findings_open():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        security=SecurityResult(
            findings=[{"file": "x.py", "type": "Key", "line": 1, "preview": "sk-****"}],
            env_files=[],
        )
    )
    assert "<details open>" in md
    assert "<summary>Potential Secrets" in md


def test_security_high_entropy_collapsed():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        security=SecurityResult(
            findings=[],
            high_entropy_strings=[{"file": "x.py", "entropy": 4.5, "line": 1, "preview": "abcdef123456"}],
            env_files=[],
        )
    )
    assert "<details>" in md
    assert "<summary>High Entropy Strings" in md
    assert "<details open>" not in md


def test_structure_not_collapsed():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        structure=StructureResult(tree="root/", file_count=1, dir_count=0)
    )
    assert "<details>" not in md


# Section ordering tests

def test_section_order():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        structure=StructureResult(tree="root/", file_count=1, dir_count=0),
        stats=StatsResult(total_files=1, total_lines=10, total_size=100, by_language={}, largest_files=[]),
        section_order=["stats", "structure"],
    )
    # Code Statistics should appear before Project Structure
    assert md.index("## Code Statistics") < md.index("## Project Structure")


def test_section_order_default():
    gen = MarkdownGenerator(Path("root"))
    md_default = gen.generate(
        structure=StructureResult(tree="root/", file_count=1, dir_count=0),
        stats=StatsResult(total_files=1, total_lines=10, total_size=100, by_language={}, largest_files=[]),
    )
    md_ordered = gen.generate(
        structure=StructureResult(tree="root/", file_count=1, dir_count=0),
        stats=StatsResult(total_files=1, total_lines=10, total_size=100, by_language={}, largest_files=[]),
        section_order=None,
    )
    # Both should have same structure
    assert "## Project Structure" in md_default
    assert "## Code Statistics" in md_ordered


def test_section_order_skips_missing():
    gen = MarkdownGenerator(Path("root"))
    md = gen.generate(
        stats=StatsResult(total_files=1, total_lines=10, total_size=100, by_language={}, largest_files=[]),
        section_order=["structure", "stats"],
    )
    # structure is in order but not passed, so only stats appears
    assert "## Code Statistics" in md
    assert "## Project Structure" not in md