"""AI agent-focused markdown generator for REPO_NOTES_AGENTS.md."""

from io import StringIO
from pathlib import Path

from repo_notes import __version__
from repo_notes.extractors import (
    ApiEndpointResult,
    ArchitectureResult,
    CicdResult,
    ComplexityResult,
    DatabaseResult,
    DuplicateResult,
    EnvVarsResult,
    GitResult,
    ProjectIntelligenceResult,
    ScriptsResult,
    SecurityResult,
    StatsResult,
    TodosResult,
)


class AgentsGenerator:
    """Render a compact, directive project brief for AI coding agents."""

    def __init__(self, root: Path):
        self.root = root

    def generate(
        self,
        project_intelligence: ProjectIntelligenceResult | None = None,
        stats: StatsResult | None = None,
        git: GitResult | None = None,
        arch: ArchitectureResult | None = None,
        security: SecurityResult | None = None,
        todos: TodosResult | None = None,
        scripts: ScriptsResult | None = None,
        env_vars: EnvVarsResult | None = None,
        cicd: CicdResult | None = None,
        database: DatabaseResult | None = None,
        complexity: ComplexityResult | None = None,
        duplicates: DuplicateResult | None = None,
        api_endpoints: ApiEndpointResult | None = None,
        **_unused,
    ) -> str:
        buf = StringIO()
        buf.write(f"# Agent Notes: {self.root.name}\n\n")
        buf.write(f"*Generated by repo-notes v{__version__} for AI coding agents.*\n\n")
        sections = [
            self._render_project_brief(project_intelligence, stats, git),
            self._render_workflow(project_intelligence, scripts),
            self._render_important_paths(project_intelligence, arch),
            self._render_architecture(arch),
            self._render_risks(
                security, todos, env_vars, cicd, database, complexity, duplicates, api_endpoints
            ),
            self._render_reading_order(project_intelligence, arch, complexity),
            self._render_agent_instructions(),
        ]
        buf.write("\n\n".join(section for section in sections if section.strip()))
        return buf.getvalue().rstrip() + "\n"

    def write_to(self, path_or_buf, **results) -> None:
        close = isinstance(path_or_buf, (str, Path))
        f = open(path_or_buf, "w", encoding="utf-8") if close else path_or_buf
        try:
            f.write(self.generate(**results))
        finally:
            if close:
                f.close()

    def _render_project_brief(
        self,
        project_intelligence: ProjectIntelligenceResult | None,
        stats: StatsResult | None,
        git: GitResult | None,
    ) -> str:
        lines = ["## Project Brief", ""]
        project_type = self._project_type(project_intelligence)
        lines.append(f"- This appears to be {project_type}.")
        if stats:
            languages = self._top_languages(stats)
            lines.append(
                f"- Codebase size: {stats.total_files} files, {stats.total_lines:,} lines"
                f"{languages}."
            )
        if project_intelligence and project_intelligence.total_tools:
            tools = self._tool_names(project_intelligence, limit=8)
            lines.append(
                f"- Detected tools: {', '.join(tools)}"
                f" across {project_intelligence.total_categories} categories."
            )
        if git and git.is_repo:
            lines.append(f"- Git branch: `{git.current_branch or 'unknown'}`.")
            if git.remote_url:
                lines.append(f"- Remote: `{git.remote_url}`.")
        lines.append("- Use this file for orientation; inspect source files before editing behavior.")
        return "\n".join(lines)

    def _render_workflow(
        self,
        project_intelligence: ProjectIntelligenceResult | None,
        scripts: ScriptsResult | None,
    ) -> str:
        commands = self._commands(project_intelligence, scripts)
        lines = ["## How To Work Here", ""]
        if commands:
            for label, command in commands:
                lines.append(f"- {label}: `{command}`")
        else:
            lines.append("- No runnable test, lint, or build command was detected.")
        lines.append("- Prefer the detected commands over ad hoc alternatives when validating changes.")
        return "\n".join(lines)

    def _render_important_paths(
        self,
        project_intelligence: ProjectIntelligenceResult | None,
        arch: ArchitectureResult | None,
    ) -> str:
        paths: list[tuple[str, str]] = []
        if arch:
            for path in arch.entry_points[:5]:
                paths.append((path.as_posix(), "entry point"))
        if project_intelligence:
            for category, label in (
                ("entrypoint", "key entry file"),
                ("readme", "documentation"),
                ("security_policy", "security policy"),
                ("ci", "CI configuration"),
                ("env", "environment file"),
            ):
                for path in project_intelligence.categories.get(category, [])[:4]:
                    paths.append((path.as_posix(), label))
        if arch:
            for layer, layer_paths in sorted(arch.layers.items()):
                for path in layer_paths[:2]:
                    paths.append((path.as_posix(), f"{layer} layer"))

        lines = ["## Important Paths", ""]
        for path, label in self._unique_pairs(paths)[:12]:
            lines.append(f"- `{path}` - {label}")
        if len(lines) == 2:
            lines.append("- No high-signal paths were detected from the available extractors.")
        return "\n".join(lines)

    def _render_architecture(self, arch: ArchitectureResult | None) -> str:
        lines = ["## Architecture Notes", ""]
        if not arch:
            lines.append("- Architecture extraction was not available for this run.")
            return "\n".join(lines)
        if arch.entry_points:
            entry = ", ".join(f"`{p.as_posix()}`" for p in arch.entry_points[:6])
            lines.append(f"- Entry points detected: {entry}.")
        if arch.layers:
            layer_bits = [f"{layer} ({len(paths)})" for layer, paths in sorted(arch.layers.items())]
            lines.append(f"- Detected layers: {', '.join(layer_bits)}.")
        if arch.import_graph:
            lines.append(f"- Import graph covers {len(arch.import_graph)} files.")
        if not arch.entry_points and not arch.layers and not arch.import_graph:
            lines.append("- No architecture signals were detected.")
        lines.append("- Do not infer full system behavior from this summary alone; open the target files.")
        return "\n".join(lines)

    def _render_risks(
        self,
        security: SecurityResult | None,
        todos: TodosResult | None,
        env_vars: EnvVarsResult | None,
        cicd: CicdResult | None,
        database: DatabaseResult | None,
        complexity: ComplexityResult | None,
        duplicates: DuplicateResult | None,
        api_endpoints: ApiEndpointResult | None,
    ) -> str:
        lines = ["## Risks And Cautions", ""]
        risk_lines = []

        if security:
            real = [f for f in security.findings if not self._is_test_path(f.get("file", ""))]
            test = [f for f in security.findings if self._is_test_path(f.get("file", ""))]
            if real:
                risk_lines.append(f"{len(real)} potential secret finding(s) outside tests need review.")
            if test:
                risk_lines.append(f"{len(test)} security finding(s) appear to be test fixtures.")
            if security.env_files:
                env_files = ", ".join(f"`{p.as_posix()}`" for p in security.env_files[:5])
                risk_lines.append(f"Environment files detected: {env_files}.")
            if security.high_entropy_strings:
                risk_lines.append(
                    f"{len(security.high_entropy_strings)} high-entropy string(s) were flagged."
                )

        if complexity and complexity.complex_files:
            files = ", ".join(f"`{item['file']}`" for item in complexity.complex_files[:3])
            risk_lines.append(f"Complexity hot spots: {files}.")
        if todos and todos.items:
            tags = ", ".join(f"{tag}: {count}" for tag, count in sorted(todos.count_by_tag.items()))
            risk_lines.append(f"Developer comments found: {tags}.")
        if env_vars and env_vars.variables:
            risk_lines.append(f"{len(env_vars.variables)} environment variable(s) are referenced.")
        if cicd and not self._has_ci(cicd):
            risk_lines.append("No CI/CD configuration was detected.")
        if database:
            db_files = [p.as_posix() for p in database.model_files + database.migration_files]
            if db_files and all(self._is_test_path(path) for path in db_files):
                risk_lines.append("Database/ORM signals appear only in tests.")
            elif db_files:
                risk_lines.append("Database/ORM files were detected; review migrations/models carefully.")
        if api_endpoints and api_endpoints.endpoints:
            endpoint_files = [e.get("file", "") for e in api_endpoints.endpoints]
            if all(self._is_test_path(path) for path in endpoint_files):
                risk_lines.append("API endpoint patterns appear only in tests.")
            else:
                risk_lines.append(f"{len(api_endpoints.endpoints)} API endpoint pattern(s) detected.")
        if duplicates and duplicates.total_duplicates:
            risk_lines.append(f"{duplicates.total_duplicates} duplicate file(s) detected.")

        if risk_lines:
            lines.extend(f"- {line}" for line in risk_lines)
        else:
            lines.append("- No major risks were detected from the enabled extractors.")
        return "\n".join(lines)

    def _render_reading_order(
        self,
        project_intelligence: ProjectIntelligenceResult | None,
        arch: ArchitectureResult | None,
        complexity: ComplexityResult | None,
    ) -> str:
        candidates: list[tuple[str, str]] = []
        if arch:
            for path in arch.entry_points:
                candidates.append((path.as_posix(), "understand runtime/CLI orchestration"))
        if project_intelligence:
            for path in project_intelligence.categories.get("entrypoint", []):
                candidates.append((path.as_posix(), "confirm entry behavior"))
            for path in project_intelligence.categories.get("readme", [])[:2]:
                candidates.append((path.as_posix(), "understand documented project intent"))
        if complexity:
            for item in complexity.complex_files[:5]:
                candidates.append((item["file"], "review high-complexity behavior before editing"))

        lines = ["## Recommended Reading Order", ""]
        for idx, (path, reason) in enumerate(self._unique_pairs(candidates)[:8], start=1):
            lines.append(f"{idx}. `{path}` - {reason}")
        if len(lines) == 2:
            lines.append("1. Start with the CLI entry point or main application entry file.")
            lines.append("2. Inspect nearby tests before making code changes.")
        return "\n".join(lines)

    def _render_agent_instructions(self) -> str:
        lines = ["## Agent Instructions", ""]
        lines.append("- Inspect relevant source and tests before editing behavior.")
        lines.append("- Add or update focused tests when changing extractor or generator output.")
        lines.append("- Preserve existing CLI semantics unless the user explicitly requests a change.")
        lines.append("- Treat generated notes files as outputs, not source-of-truth implementation.")
        lines.append("- Keep changes scoped; avoid unrelated refactors while working from this brief.")
        return "\n".join(lines)

    def _project_type(self, result: ProjectIntelligenceResult | None) -> str:
        if not result or not result.tools:
            return "a software project"
        languages = [tool.name for tool in result.tools.get("Languages", [])]
        frameworks = [tool.name for tool in result.tools.get("Frameworks", [])]
        mobile = [tool.name for tool in result.tools.get("Mobile", [])]
        parts = languages[:2]
        if frameworks:
            parts.append(frameworks[0])
        if mobile:
            parts.append(mobile[0])
        if parts:
            return "a " + " / ".join(parts) + " project"
        return "a software project"

    def _top_languages(self, stats: StatsResult) -> str:
        langs = [
            lang
            for lang, _data in sorted(
                stats.by_language.items(), key=lambda item: item[1]["lines"], reverse=True
            )
            if lang != "unknown"
        ][:3]
        return f" across {', '.join(langs)}" if langs else ""

    def _tool_names(self, result: ProjectIntelligenceResult, limit: int) -> list[str]:
        names: list[str] = []
        for category in ("Languages", "Frameworks", "Build", "Testing", "Linting", "Mobile"):
            names.extend(tool.name for tool in result.tools.get(category, []))
        return list(dict.fromkeys(names))[:limit]

    def _commands(
        self,
        project_intelligence: ProjectIntelligenceResult | None,
        scripts: ScriptsResult | None,
    ) -> list[tuple[str, str]]:
        commands: list[tuple[str, str]] = []
        if scripts:
            for name, command in sorted(scripts.package_json.items()):
                if name in {"test", "lint", "build", "typecheck", "dev"}:
                    commands.append((f"npm script `{name}`", f"npm run {name}"))
            for target in scripts.makefile_targets[:5]:
                commands.append((f"Make target `{target}`", f"make {target}"))
            for recipe in scripts.justfile_recipes[:5]:
                commands.append((f"Just recipe `{recipe}`", f"just {recipe}"))
            for name in sorted(scripts.pyproject_scripts):
                commands.append((f"Python console script `{name}`", name))

        tool_names = {
            tool.name.lower()
            for tools in (project_intelligence.tools.values() if project_intelligence else [])
            for tool in tools
        }
        if "pytest" in tool_names and not self._has_command(commands, "pytest"):
            commands.append(("Tests", "pytest"))
        if "ruff" in tool_names and not self._has_command(commands, "ruff"):
            commands.append(("Lint", "ruff check src/ tests/"))
        return commands[:10]

    def _has_command(self, commands: list[tuple[str, str]], needle: str) -> bool:
        return any(needle in command for _label, command in commands)

    def _has_ci(self, cicd: CicdResult) -> bool:
        return bool(
            cicd.github_actions or cicd.gitlab_ci or cicd.circleci or cicd.jenkins_stages
        )

    def _unique_pairs(self, items: list[tuple[str, str]]) -> list[tuple[str, str]]:
        seen = set()
        unique = []
        for path, label in items:
            if path in seen:
                continue
            seen.add(path)
            unique.append((path, label))
        return unique

    def _is_test_path(self, path: str) -> bool:
        normalized = path.replace("\\", "/").lower()
        return (
            normalized.startswith("tests/")
            or "/tests/" in normalized
            or normalized.startswith("test/")
            or "/test/" in normalized
            or normalized.split("/")[-1].startswith("test_")
            or normalized.split("/")[-1].endswith("_test.py")
        )
