"""Markdown generator for REPO_NOTES.md."""

from io import StringIO
from pathlib import Path
from repo_notes.extractors import (
    StructureResult,
    KeyFilesResult,
    StatsResult,
    DependenciesResult,
    GitResult,
    ArchitectureResult,
    SecurityResult,
    TodosResult,
    ScriptsResult,
    EnvVarsResult,
    CicdResult,
    DatabaseResult,
    TypeCoverageResult,
    ComplexityResult,
    DuplicateResult,
)

SECTION_NAMES: dict[str, str] = {
    "structure": "Project Structure",
    "key_files": "Key Files",
    "stats": "Code Statistics",
    "deps": "Dependencies",
    "git": "Git Information",
    "arch": "Architecture Overview",
    "security": "Security Notes",
    "todos": "TODO / FIXME / HACK",
    "scripts": "Build Scripts",
    "env_vars": "Environment Variables",
    "cicd": "CI/CD Configuration",
    "database": "Database Schema",
    "type_coverage": "Type Coverage",
    "complexity": "Code Complexity",
    "duplicates": "Duplicate Files",
}


class MarkdownGenerator:
    def __init__(self, root: Path):
        self.root = root

    def generate(
        self,
        structure: StructureResult | None = None,
        key_files: KeyFilesResult | None = None,
        stats: StatsResult | None = None,
        deps: DependenciesResult | None = None,
        git: GitResult | None = None,
        arch: ArchitectureResult | None = None,
        security: SecurityResult | None = None,
        section_order: list[str] | None = None,
    ) -> str:
        buf = StringIO()
        self._stream_write(buf, section_order=section_order, structure=structure, key_files=key_files, stats=stats, deps=deps, git=git, arch=arch, security=security)
        output = buf.getvalue()
        return "\n\n".join(s.rstrip() for s in output.split("\n\n") if s.strip()) + "\n"

    def write_to(self, path_or_buf, **results) -> None:
        """Stream output to a file or file-like object without building the full string in memory."""
        close = isinstance(path_or_buf, (str, Path))
        f = open(path_or_buf, "w", encoding="utf-8") if close else path_or_buf
        try:
            self._stream_write(f, **results)
        finally:
            if close:
                f.close()

    def _stream_write(self, f, **results) -> None:
        """Write all sections progressively to a file-like object."""
        title = f"# Repository Notes: {self.root.name}\n\n*Generated by repo-notes v0.1.0*"
        badges = self._render_badges(
            stats=results.get("stats"),
            security=results.get("security"),
            git=results.get("git"),
        )
        if badges:
            title += f"\n\n{badges}"
        f.write(title + "\n\n")

        results_map = {
            "structure": results.get("structure"),
            "key_files": results.get("key_files"),
            "stats": results.get("stats"),
            "deps": results.get("deps"),
            "git": results.get("git") if results.get("git") and getattr(results.get("git"), "is_repo", False) else None,
            "arch": results.get("arch"),
            "security": results.get("security"),
            "todos": results.get("todos"),
            "scripts": results.get("scripts"),
            "env_vars": results.get("env_vars"),
            "cicd": results.get("cicd"),
            "database": results.get("database"),
            "type_coverage": results.get("type_coverage"),
            "complexity": results.get("complexity"),
            "duplicates": results.get("duplicates"),
        }

        renderers = {
            "structure": self._render_structure,
            "key_files": self._render_key_files,
            "stats": self._render_stats,
            "deps": self._render_dependencies,
            "git": self._render_git,
            "arch": self._render_architecture,
            "security": self._render_security,
            "todos": self._render_todos,
            "scripts": self._render_scripts,
            "env_vars": self._render_env_vars,
            "cicd": self._render_cicd,
            "database": self._render_database,
            "type_coverage": self._render_type_coverage,
            "complexity": self._render_complexity,
            "duplicates": self._render_duplicates,
        }

        order = results.get("section_order") or list(SECTION_NAMES.keys())

        written = 0
        for name in order:
            if name not in renderers:
                continue
            result = results_map.get(name)
            if result is not None:
                if written > 0:
                    f.write("\n\n")
                f.write(renderers[name](result))
                written += 1

    def _render_badges(
        self,
        stats: StatsResult | None = None,
        security: SecurityResult | None = None,
        git: GitResult | None = None,
    ) -> str:
        parts = []
        if stats:
            parts.append(f"**{stats.total_files}** files")
            parts.append(f"**{stats.total_lines:,}** lines")
            parts.append(self._format_size(stats.total_size))
            langs = len(stats.by_language)
            if langs:
                parts.append(f"**{langs}** languages")
        if security:
            high = len(security.findings)
            mild = len(security.high_entropy_strings)
            labels = []
            if high:
                labels.append(f"**{high}** high")
            if mild:
                labels.append(f"**{mild}** mild")
            if not high and not mild:
                labels.append("**0** issues")
            parts.append(" · ".join(labels))
        if git and git.is_repo:
            parts.append(f"branch **{git.current_branch}**")
        return " · ".join(parts) if parts else ""

    def _collapse(self, summary: str, content: str) -> str:
        return f"<details>\n<summary>{summary}</summary>\n\n{content}\n\n</details>"

    def _render_structure(self, result: StructureResult) -> str:
        lines = ["## Project Structure", "", "```text", result.tree, "```", ""]
        lines.append(f"*{result.file_count} files, {result.dir_count} directories*")
        return "\n".join(lines)

    def _render_key_files(self, result: KeyFilesResult) -> str:
        lines = ["## Key Files", ""]
        for cat, files in result.categories.items():
            if not files:
                continue
            lines.append(f"### {cat.replace('_', ' ').title()}")
            for f in sorted(files):
                lines.append(f"- `{f}`")
            lines.append("")
        return "\n".join(lines)

    def _render_stats(self, result: StatsResult) -> str:
        lines = ["## Code Statistics", ""]
        lines.append(f"- **Total files**: {result.total_files}")
        lines.append(f"- **Total lines**: {result.total_lines:,}")
        lines.append(f"- **Total size**: {self._format_size(result.total_size)}")
        lines.append("")

        if result.by_language:
            table = [
                "### By Language",
                "",
                "| Language | Files | Lines | Size |",
                "|----------|-------|-------|------|",
            ]
            for lang, data in sorted(result.by_language.items(), key=lambda x: -x[1]["lines"]):
                table.append(f"| {lang} | {data['files']} | {data['lines']:,} | {self._format_size(data['size'])} |")
            table.append("")
            lines.append(self._collapse(
                f"By Language ({len(result.by_language)} languages)",
                "\n".join(table),
            ))
            lines.append("")

        if result.largest_files:
            files_list = ["### Largest Files", ""]
            for path, lines_count in result.largest_files:
                files_list.append(f"- `{path}` — {lines_count:,} lines")
            files_list.append("")
            lines.append(self._collapse(
                f"Largest Files (top {len(result.largest_files)})",
                "\n".join(files_list),
            ))
            lines.append("")

        return "\n".join(lines)

    def _render_dependencies(self, result: DependenciesResult) -> str:
        lines = ["## Dependencies", ""]

        for ecosystem, data in [
            ("Python", result.python),
            ("JavaScript/TypeScript", result.javascript),
            ("Go", result.go),
            ("Rust", result.rust),
        ]:
            if not data:
                continue
            eco_lines = [f"### {ecosystem}"]
            for file, deps in data.items():
                eco_lines.append(f"**{file}**")
                if isinstance(deps, dict):
                    for key, val in deps.items():
                        if isinstance(val, dict):
                            eco_lines.append(f"  - {key}: {len(val)} packages")
                        elif isinstance(val, list):
                            eco_lines.append(f"  - {key}: {len(val)} entries")
                        else:
                            eco_lines.append(f"  - {key}: {val}")
                else:
                    eco_lines.append(f"  - {deps}")
            eco_lines.append("")
            lines.append(self._collapse(
                f"{ecosystem} ({len(data)} files)",
                "\n".join(eco_lines),
            ))
            lines.append("")

        return "\n".join(lines)

    def _render_git(self, result: GitResult) -> str:
        lines = ["## Git Information", ""]
        lines.append(f"- **Current branch**: {result.current_branch}")
        if result.remote_url:
            lines.append(f"- **Remote**: {result.remote_url}")
        lines.append("")

        if result.recent_commits:
            lines.append("### Recent Commits")
            lines.append("")
            lines.append("| Hash | Author | Date | Message |")
            lines.append("|------|--------|------|---------|")
            for c in result.recent_commits:
                lines.append(f"| {c['hash']} | {c['author']} | {c['date']} | {c['message'][:60]}... |")
            lines.append("")

        if result.branches:
            branches_lines = ["### Branches", ""]
            for b in result.branches[:20]:
                branches_lines.append(f"- {b}")
            if len(result.branches) > 20:
                branches_lines.append(f"- *...and {len(result.branches) - 20} more*")
            branches_lines.append("")
            lines.append(self._collapse(
                f"Branches ({len(result.branches)})",
                "\n".join(branches_lines),
            ))
            lines.append("")

        if result.contributors:
            contrib_lines = ["### Top Contributors", ""]
            contrib_lines.append("| Contributor | Commits |")
            contrib_lines.append("|-------------|---------|")
            for c in result.contributors[:10]:
                contrib_lines.append(f"| {c['name']} | {c['commits']} |")
            contrib_lines.append("")
            lines.append(self._collapse(
                f"Top Contributors ({len(result.contributors)})",
                "\n".join(contrib_lines),
            ))
            lines.append("")

        return "\n".join(lines)

    def _render_architecture(self, result: ArchitectureResult) -> str:
        lines = ["## Architecture Overview", ""]

        if result.layers:
            layer_lines = ["### Detected Layers", ""]
            for layer, files in sorted(result.layers.items()):
                layer_lines.append(f"**{layer.title()}** ({len(files)} files)")
                for f in sorted(files)[:10]:
                    layer_lines.append(f"  - `{f}`")
                if len(files) > 10:
                    layer_lines.append(f"  - *...and {len(files) - 10} more*")
                layer_lines.append("")
            lines.append(self._collapse(
                f"Detected Layers ({len(result.layers)})",
                "\n".join(layer_lines),
            ))
            lines.append("")

        if result.entry_points:
            lines.append("### Entry Points")
            lines.append("")
            for f in sorted(result.entry_points):
                lines.append(f"- `{f}`")
            lines.append("")

        return "\n".join(lines)

    def _render_security(self, result: SecurityResult) -> str:
        lines = ["## Security Notes", ""]

        if result.env_files:
            lines.append("### Environment Files Found")
            lines.append("")
            for f in result.env_files:
                lines.append(f"- `{f}` ⚠️")
            lines.append("")

        if result.findings:
            findings_lines = ["### Potential Secrets Detected", ""]
            findings_lines.append("| File | Type | Line | Preview |")
            findings_lines.append("|------|------|------|---------|")
            for f in result.findings[:30]:
                findings_lines.append(f"| `{f['file']}` | {f['type']} | {f['line']} | `{f['preview']}` |")
            if len(result.findings) > 30:
                findings_lines.append(f"| *...and {len(result.findings) - 30} more* | | | |")
            findings_lines.append("")
            lines.append(f"<details open>\n<summary>Potential Secrets ({len(result.findings)} detected)</summary>\n\n" + "\n".join(findings_lines) + "\n</details>")
            lines.append("")

        if result.high_entropy_strings:
            entropy_lines = ["### High Entropy Strings (Review Recommended)", ""]
            entropy_lines.append("| File | Entropy | Line | Preview |")
            entropy_lines.append("|------|---------|------|---------|")
            for f in result.high_entropy_strings[:20]:
                entropy_lines.append(f"| `{f['file']}` | {f['entropy']} | {f['line']} | `{f['preview']}` |")
            entropy_lines.append("")
            lines.append(f"<details>\n<summary>High Entropy Strings ({len(result.high_entropy_strings)} found, review recommended)</summary>\n\n" + "\n".join(entropy_lines) + "\n</details>")
            lines.append("")

        return "\n".join(lines)

    def _render_todos(self, result: TodosResult) -> str:
        lines = ["## TODO / FIXME / HACK", ""]
        if not result.items:
            lines.append("No developer comments found.")
            return "\n".join(lines)

        tag_order = ["FIXME", "HACK", "TODO", "XXX", "BUG", "WORKAROUND", "HACKME"]
        for tag in tag_order:
            tag_items = [i for i in result.items if i["tag"] == tag]
            if not tag_items:
                continue
            total = result.count_by_tag.get(tag, 0)
            lines.append(f"### {tag} ({total} total)")

            if total > len(tag_items):
                lines.append(f"*Showing top {len(tag_items)} of {total}*")

            lines.append("")
            lines.append("| File | Line | Message |")
            lines.append("|------|------|---------|")
            for item in tag_items:
                msg = item["message"].replace("|", "\\|") if item["message"] else "—"
                lines.append(f"| `{item['file']}` | {item['line']} | {msg} |")
            lines.append("")
        return "\n".join(lines)

    def _render_scripts(self, result: ScriptsResult) -> str:
        lines = ["## Build Scripts", ""]
        has_any = False

        if result.package_json:
            has_any = True
            lines.append("### package.json Scripts")
            lines.append("")
            for name, cmd in sorted(result.package_json.items()):
                lines.append(f"- **{name}**: `{cmd}`")
            lines.append("")

        if result.makefile_targets:
            has_any = True
            lines.append("### Makefile Targets")
            lines.append("")
            for t in result.makefile_targets[:30]:
                lines.append(f"- `{t}`")
            if len(result.makefile_targets) > 30:
                lines.append(f"- *...and {len(result.makefile_targets) - 30} more*")
            lines.append("")

        if result.justfile_recipes:
            has_any = True
            lines.append("### Justfile Recipes")
            lines.append("")
            for r in result.justfile_recipes[:30]:
                lines.append(f"- `{r}`")
            if len(result.justfile_recipes) > 30:
                lines.append(f"- *...and {len(result.justfile_recipes) - 30} more*")
            lines.append("")

        if result.pyproject_scripts:
            has_any = True
            lines.append("### pyproject.toml Scripts")
            lines.append("")
            for name, cmd in sorted(result.pyproject_scripts.items()):
                lines.append(f"- **{name}**: `{cmd}`")
            lines.append("")

        if not has_any:
            lines.append("No build scripts found.")

        return "\n".join(lines)

    def _render_env_vars(self, result: EnvVarsResult) -> str:
        lines = ["## Environment Variables", ""]
        if not result.variables:
            lines.append("No environment variable references found.")
            return "\n".join(lines)

        lines.append(f"**{len(result.variables)}** unique environment variables referenced.")
        lines.append("")
        lines.append("| Variable | Files |")
        lines.append("|----------|-------|")
        for var, files in list(result.variables.items())[:40]:
            files_str = ", ".join(f"`{f}`" for f in files[:5])
            if len(files) > 5:
                files_str += f", *...and {len(files) - 5} more*"
            lines.append(f"| `{var}` | {files_str} |")
        if len(result.variables) > 40:
            lines.append(f"| *...and {len(result.variables) - 40} more* | |")
        lines.append("")
        return "\n".join(lines)

    def _render_cicd(self, result: CicdResult) -> str:
        lines = ["## CI/CD Configuration", ""]
        has_any = False

        if result.github_actions:
            has_any = True
            lines.append("### GitHub Actions")
            for wf in result.github_actions:
                on = ", ".join(wf["on"]) if isinstance(wf["on"], list) else wf["on"]
                jobs = ", ".join(wf["jobs"][:8])
                if len(wf["jobs"]) > 8:
                    jobs += f", ..."
                lines.append(f"- **{wf['name']}** — on {on}")
                lines.append(f"  - Jobs: {jobs}")
            lines.append("")

        if result.gitlab_ci:
            has_any = True
            stages = set(j["stage"] for j in result.gitlab_ci)
            lines.append(f"### GitLab CI — Stages: {', '.join(sorted(stages))}")
            for job in result.gitlab_ci:
                img = f" ({job['image']})" if job["image"] else ""
                lines.append(f"- **{job['name']}** (stage: {job['stage']}){img}")
            lines.append("")

        if result.circleci:
            has_any = True
            lines.append("### CircleCI Jobs")
            for job in result.circleci:
                lines.append(f"- **{job['name']}** — {job['steps']} steps")
            lines.append("")

        if result.jenkins_stages:
            has_any = True
            lines.append("### Jenkins Pipeline Stages")
            for s in result.jenkins_stages:
                lines.append(f"- {s}")
            lines.append("")

        if not has_any:
            lines.append("No CI/CD configuration found.")
        return "\n".join(lines)

    def _render_database(self, result: DatabaseResult) -> str:
        lines = ["## Database Schema", ""]
        has_any = False

        if result.orm_types:
            has_any = True
            lines.append("### Detected ORM")
            for t in result.orm_types:
                lines.append(f"- **{t}**")
            lines.append("")

        if result.model_count:
            has_any = True
            lines.append(f"- **{result.model_count}** models across {len(result.model_files)} files")
            lines.append("")

        if result.migration_files:
            has_any = True
            lines.append(f"### Migration Files ({len(result.migration_files)})")
            for m in result.migration_files[:15]:
                lines.append(f"- `{m}`")
            if len(result.migration_files) > 15:
                lines.append(f"- *...and {len(result.migration_files) - 15} more*")
            lines.append("")

        if result.schema_files:
            has_any = True
            lines.append("### Schema Files")
            for s in result.schema_files:
                lines.append(f"- `{s}`")
            lines.append("")

        if result.model_files:
            has_any = True
            lines.append(f"### Model Files ({len(result.model_files)})")
            for m in result.model_files[:15]:
                lines.append(f"- `{m}`")
            if len(result.model_files) > 15:
                lines.append(f"- *...and {len(result.model_files) - 15} more*")
            lines.append("")

        if not has_any:
            lines.append("No database schema detected.")
        return "\n".join(lines)

    def _render_type_coverage(self, result: TypeCoverageResult) -> str:
        lines = ["## Type Coverage", ""]
        if result.typed_files == 0 and result.untyped_files == 0:
            lines.append("No typed or untyped files found.")
            return "\n".join(lines)

        total = result.typed_files + result.untyped_files
        pct = round(result.typed_files / total * 100, 1) if total else 0
        lines.append(f"- **{pct}%** of files are typed")
        lines.append(f"- {result.typed_files} typed files, {result.untyped_files} untyped files")
        lines.append(f"- {result.typed_lines:,} typed lines, {result.untyped_lines:,} untyped lines")
        lines.append("")

        if result.by_extension:
            lines.append("### By Extension")
            lines.append("")
            lines.append("| Extension | Files | Typed Lines | Untyped Lines |")
            lines.append("|-----------|-------|-------------|---------------|")
            for ext, data in sorted(result.by_extension.items()):
                lines.append(f"| {ext} | {data['files']} | {data['typed_lines']:,} | {data['untyped_lines']:,} |")
            lines.append("")

        return "\n".join(lines)

    def _render_complexity(self, result: ComplexityResult) -> str:
        lines = ["## Code Complexity", ""]

        lines.append(f"- **Average function length**: {result.avg_function_length} lines")
        lines.append(f"- **Max nesting depth**: {result.max_nesting}")
        lines.append("")

        if result.complex_files:
            lines.append(f"### Complex Files ({len(result.complex_files)})")
            lines.append("")
            lines.append("| File | Long Functions | Max Nesting | Score |")
            lines.append("|------|---------------|-------------|-------|")
            for entry in result.complex_files:
                n_long = len(entry["long_functions"])
                lines.append(f"| `{entry['file']}` | {n_long} | {entry['max_nesting']} | {entry['score']} |")
            lines.append("")
        else:
            lines.append("No complex files detected.")

        return "\n".join(lines)

    def _render_duplicates(self, result: DuplicateResult) -> str:
        lines = ["## Duplicate Files", ""]

        if result.total_duplicates == 0:
            lines.append("No duplicate files found.")
            return "\n".join(lines)

        lines.append(f"- **{result.total_duplicates}** duplicate file(s) found")
        if result.total_saved_bytes:
            lines.append(f"- **{self._format_size(result.total_saved_bytes)}** could be saved")
        lines.append("")

        lines.append("| Duplicate File | Original | Size | Similarity |")
        lines.append("|----------------|----------|------|------------|")
        for dup in result.duplicates[:20]:
            sim = f"{dup['similarity']*100:.0f}%"
            lines.append(f"| `{dup['file']}` | `{dup['duplicate_of']}` | {self._format_size(dup['size'])} | {sim} |")
        if len(result.duplicates) > 20:
            lines.append(f"| *...and {len(result.duplicates) - 20} more* | | | |")
        lines.append("")

        return "\n".join(lines)

    def _format_size(self, size: int) -> str:
        for unit in ["B", "KB", "MB", "GB"]:
            if size < 1024:
                return f"{size:.1f} {unit}"
            size /= 1024
        return f"{size:.1f} TB"