"""Markdown generator for REPO_NOTES.md."""

from pathlib import Path
from repo_notes.extractors import (
    StructureResult,
    KeyFilesResult,
    StatsResult,
    DependenciesResult,
    GitResult,
    ArchitectureResult,
    SecurityResult,
)


class MarkdownGenerator:
    def __init__(self, root: Path):
        self.root = root

    def generate(
        self,
        structure: StructureResult | None = None,
        key_files: KeyFilesResult | None = None,
        stats: StatsResult | None = None,
        deps: DependenciesResult | None = None,
        git: GitResult | None = None,
        arch: ArchitectureResult | None = None,
        security: SecurityResult | None = None,
    ) -> str:
        sections = [f"# Repository Notes: {self.root.name}\n\n*Generated by repo-notes v0.1.0*"]

        if structure:
            sections.append(self._render_structure(structure))

        if key_files:
            sections.append(self._render_key_files(key_files))

        if stats:
            sections.append(self._render_stats(stats))

        if deps:
            sections.append(self._render_dependencies(deps))

        if git and git.is_repo:
            sections.append(self._render_git(git))

        if arch:
            sections.append(self._render_architecture(arch))

        if security:
            sections.append(self._render_security(security))

        return "\n\n".join(s.rstrip() for s in sections if s.strip()) + "\n"

    def _render_structure(self, result: StructureResult) -> str:
        lines = ["## Project Structure", "", "```text", result.tree, "```", ""]
        lines.append(f"*{result.file_count} files, {result.dir_count} directories*")
        return "\n".join(lines)

    def _render_key_files(self, result: KeyFilesResult) -> str:
        lines = ["## Key Files", ""]
        for cat, files in result.categories.items():
            if not files:
                continue
            lines.append(f"### {cat.replace('_', ' ').title()}")
            for f in sorted(files):
                lines.append(f"- `{f}`")
            lines.append("")
        return "\n".join(lines)

    def _render_stats(self, result: StatsResult) -> str:
        lines = ["## Code Statistics", ""]
        lines.append(f"- **Total files**: {result.total_files}")
        lines.append(f"- **Total lines**: {result.total_lines:,}")
        lines.append(f"- **Total size**: {self._format_size(result.total_size)}")
        lines.append("")

        if result.by_language:
            lines.append("### By Language")
            lines.append("")
            lines.append("| Language | Files | Lines | Size |")
            lines.append("|----------|-------|-------|------|")
            for lang, data in sorted(result.by_language.items(), key=lambda x: -x[1]["lines"]):
                lines.append(f"| {lang} | {data['files']} | {data['lines']:,} | {self._format_size(data['size'])} |")
            lines.append("")

        if result.largest_files:
            lines.append("### Largest Files")
            lines.append("")
            for path, lines_count in result.largest_files:
                lines.append(f"- `{path}` — {lines_count:,} lines")
            lines.append("")

        return "\n".join(lines)

    def _render_dependencies(self, result: DependenciesResult) -> str:
        lines = ["## Dependencies", ""]

        for ecosystem, data in [
            ("Python", result.python),
            ("JavaScript/TypeScript", result.javascript),
            ("Go", result.go),
            ("Rust", result.rust),
        ]:
            if not data:
                continue
            lines.append(f"### {ecosystem}")
            for file, deps in data.items():
                lines.append(f"**{file}**")
                if isinstance(deps, dict):
                    for key, val in deps.items():
                        if isinstance(val, dict):
                            lines.append(f"  - {key}: {len(val)} packages")
                        elif isinstance(val, list):
                            lines.append(f"  - {key}: {len(val)} entries")
                        else:
                            lines.append(f"  - {key}: {val}")
                else:
                    lines.append(f"  - {deps}")
            lines.append("")

        return "\n".join(lines)

    def _render_git(self, result: GitResult) -> str:
        lines = ["## Git Information", ""]
        lines.append(f"- **Current branch**: {result.current_branch}")
        if result.remote_url:
            lines.append(f"- **Remote**: {result.remote_url}")
        lines.append("")

        if result.recent_commits:
            lines.append("### Recent Commits")
            lines.append("")
            lines.append("| Hash | Author | Date | Message |")
            lines.append("|------|--------|------|---------|")
            for c in result.recent_commits:
                lines.append(f"| {c['hash']} | {c['author']} | {c['date']} | {c['message'][:60]}... |")
            lines.append("")

        if result.branches:
            lines.append("### Branches")
            lines.append("")
            for b in result.branches[:20]:
                lines.append(f"- {b}")
            if len(result.branches) > 20:
                lines.append(f"- *...and {len(result.branches) - 20} more*")
            lines.append("")

        if result.contributors:
            lines.append("### Top Contributors")
            lines.append("")
            lines.append("| Contributor | Commits |")
            lines.append("|-------------|---------|")
            for c in result.contributors[:10]:
                lines.append(f"| {c['name']} | {c['commits']} |")
            lines.append("")

        return "\n".join(lines)

    def _render_architecture(self, result: ArchitectureResult) -> str:
        lines = ["## Architecture Overview", ""]

        if result.layers:
            lines.append("### Detected Layers")
            lines.append("")
            for layer, files in sorted(result.layers.items()):
                lines.append(f"**{layer.title()}** ({len(files)} files)")
                for f in sorted(files)[:10]:
                    lines.append(f"  - `{f}`")
                if len(files) > 10:
                    lines.append(f"  - *...and {len(files) - 10} more*")
                lines.append("")

        if result.entry_points:
            lines.append("### Entry Points")
            lines.append("")
            for f in sorted(result.entry_points):
                lines.append(f"- `{f}`")
            lines.append("")

        return "\n".join(lines)

    def _render_security(self, result: SecurityResult) -> str:
        lines = ["## Security Notes", ""]

        if result.env_files:
            lines.append("### Environment Files Found")
            lines.append("")
            for f in result.env_files:
                lines.append(f"- `{f}` ⚠️")
            lines.append("")

        if result.findings:
            lines.append("### Potential Secrets Detected")
            lines.append("")
            lines.append("| File | Type | Line | Preview |")
            lines.append("|------|------|------|---------|")
            for f in result.findings[:30]:
                lines.append(f"| `{f['file']}` | {f['type']} | {f['line']} | `{f['preview']}` |")
            if len(result.findings) > 30:
                lines.append(f"| *...and {len(result.findings) - 30} more* | | | |")
            lines.append("")

        if result.high_entropy_strings:
            lines.append("### High Entropy Strings (Review Recommended)")
            lines.append("")
            lines.append("| File | Entropy | Line | Preview |")
            lines.append("|------|---------|------|---------|")
            for f in result.high_entropy_strings[:20]:
                lines.append(f"| `{f['file']}` | {f['entropy']} | {f['line']} | `{f['preview']}` |")
            lines.append("")

        return "\n".join(lines)

    def _format_size(self, size: int) -> str:
        for unit in ["B", "KB", "MB", "GB"]:
            if size < 1024:
                return f"{size:.1f} {unit}"
            size /= 1024
        return f"{size:.1f} TB"