"""Markdown generator for REPO_NOTES.md."""

from io import StringIO
from pathlib import Path

from repo_notes import __version__
from repo_notes.extractors import (
    ApiEndpointResult,
    ArchitectureResult,
    CicdResult,
    ComplexityResult,
    DatabaseResult,
    DependenciesResult,
    DuplicateResult,
    EnvVarsResult,
    GitResult,
    ProjectIntelligenceResult,
    ScriptsResult,
    SecurityResult,
    StatsResult,
    StructureResult,
    TodosResult,
    TypeCoverageResult,
)

SECTION_NAMES: dict[str, str] = {
    "structure": "Project Structure",
    "project_intelligence": "Project Intelligence",
    "stats": "Code Statistics",
    "deps": "Dependencies",
    "git": "Git Information",
    "arch": "Architecture Overview",
    "security": "Security Notes",
    "todos": "TODO / FIXME / HACK",
    "scripts": "Build Scripts",
    "env_vars": "Environment Variables",
    "cicd": "CI/CD Configuration",
    "database": "Database Schema",
    "type_coverage": "Type Coverage",
    "complexity": "Code Complexity",
    "duplicates": "Duplicate Files",
    "api_endpoints": "API Endpoints",
}


class MarkdownGenerator:
    def __init__(self, root: Path):
        self.root = root

    def generate(
        self,
        structure: StructureResult | None = None,
        project_intelligence: ProjectIntelligenceResult | None = None,
        stats: StatsResult | None = None,
        deps: DependenciesResult | None = None,
        git: GitResult | None = None,
        arch: ArchitectureResult | None = None,
        security: SecurityResult | None = None,
        todos: TodosResult | None = None,
        scripts: ScriptsResult | None = None,
        env_vars: EnvVarsResult | None = None,
        cicd: CicdResult | None = None,
        database: DatabaseResult | None = None,
        type_coverage: TypeCoverageResult | None = None,
        complexity: ComplexityResult | None = None,
        duplicates: DuplicateResult | None = None,
        api_endpoints: ApiEndpointResult | None = None,
        section_order: list[str] | None = None,
    ) -> str:
        buf = StringIO()
        self._stream_write(buf, section_order=section_order,
            structure=structure, project_intelligence=project_intelligence,
            stats=stats, deps=deps, git=git, arch=arch, security=security,
            todos=todos, scripts=scripts, env_vars=env_vars, cicd=cicd,
            database=database, type_coverage=type_coverage,
            complexity=complexity, duplicates=duplicates,
            api_endpoints=api_endpoints)
        output = buf.getvalue()
        return "\n\n".join(s.rstrip() for s in output.split("\n\n") if s.strip()) + "\n"

    def write_to(self, path_or_buf, **results) -> None:
        """Stream output to a file or file-like object without building the full string in memory."""
        close = isinstance(path_or_buf, (str, Path))
        f = open(path_or_buf, "w", encoding="utf-8") if close else path_or_buf
        try:
            self._stream_write(f, **results)
        finally:
            if close:
                f.close()

    def _stream_write(self, f, **results) -> None:
        """Write all sections progressively to a file-like object."""
        title = f"# Repository Notes: {self.root.name}\n\n*Generated by repo-notes v{__version__}*"
        badges = self._render_badges(
            stats=results.get("stats"),
            security=results.get("security"),
            git=results.get("git"),
        )
        if badges:
            title += f"\n\n{badges}"
        f.write(title + "\n\n")

        results_map = {
            "structure": results.get("structure"),
            "project_intelligence": results.get("project_intelligence"),
            "stats": results.get("stats"),
            "deps": results.get("deps"),
            "git": results.get("git") if results.get("git") and getattr(results.get("git"), "is_repo", False) else None,
            "arch": results.get("arch"),
            "security": results.get("security"),
            "todos": results.get("todos"),
            "scripts": results.get("scripts"),
            "env_vars": results.get("env_vars"),
            "cicd": results.get("cicd"),
            "database": results.get("database"),
            "type_coverage": results.get("type_coverage"),
            "complexity": results.get("complexity"),
            "duplicates": results.get("duplicates"),
            "api_endpoints": results.get("api_endpoints"),
        }

        renderers = {
            "structure": self._render_structure,
            "project_intelligence": self._render_project_intelligence,
            "stats": self._render_stats,
            "deps": self._render_dependencies,
            "git": self._render_git,
            "arch": self._render_architecture,
            "security": self._render_security,
            "todos": self._render_todos,
            "scripts": self._render_scripts,
            "env_vars": self._render_env_vars,
            "cicd": self._render_cicd,
            "database": self._render_database,
            "type_coverage": self._render_type_coverage,
            "complexity": self._render_complexity,
            "duplicates": self._render_duplicates,
            "api_endpoints": self._render_api_endpoints,
        }

        order = results.get("section_order") or list(SECTION_NAMES.keys())

        written = 0
        for name in order:
            if name not in renderers:
                continue
            result = results_map.get(name)
            if result is not None:
                if written > 0:
                    f.write("\n\n")
                f.write(renderers[name](result))
                written += 1

    def _render_badges(
        self,
        stats: StatsResult | None = None,
        security: SecurityResult | None = None,
        git: GitResult | None = None,
    ) -> str:
        parts = []
        if stats:
            parts.append(f"**{stats.total_files}** files")
            parts.append(f"**{stats.total_lines:,}** lines")
            parts.append(self._format_size(stats.total_size))
            langs = len(stats.by_language)
            if langs:
                parts.append(f"**{langs}** languages")
        if security:
            high = len(security.findings)
            mild = len(security.high_entropy_strings)
            labels = []
            if high:
                labels.append(f"**{high}** high")
            if mild:
                labels.append(f"**{mild}** mild")
            if not high and not mild:
                labels.append("**0** issues")
            parts.append(" · ".join(labels))
        if git and git.is_repo:
            parts.append(f"branch **{git.current_branch}**")
        return " · ".join(parts) if parts else ""

    def _escape_md_table(self, s: str) -> str:
        return s.replace("|", "\\|")

    def _collapse(self, summary: str, content: str) -> str:
        return f"<details>\n<summary>{summary}</summary>\n\n{content}\n\n</details>"

    def _render_structure(self, result: StructureResult) -> str:
        lines = ["## Project Structure", "", "```text", result.tree, "```", ""]
        lines.append(f"*{result.file_count} files, {result.dir_count} directories*")
        return "\n".join(lines)

    def _render_project_intelligence(self, result: ProjectIntelligenceResult) -> str:
        lines = ["## Project Intelligence", ""]

        by_cat_order = [
            "Languages", "Frameworks", "Build", "Testing", "Linting",
            "Database", "Messaging", "Containers", "Cloud",
            "Monitoring", "Documentation", "Automation", "Mobile", "Utilities",
        ]

        total = result.total_tools
        lines.append(f"**{total}** tools detected across **{result.total_categories}** categories.")
        lines.append("")

        for cat in by_cat_order:
            tools = result.tools.get(cat)
            if not tools:
                continue
            lines.append(f"### {cat} ({len(tools)})")
            lines.append("")
            lines.append("| Tool | Version | Config |")
            lines.append("|------|---------|--------|")
            for t in sorted(tools, key=lambda x: x.name.lower()):
                ver = t.version or "—"
                cfg = f"`{t.config_file}`" if t.config_file else "—"
                lines.append(f"| **{t.name}** | {ver} | {cfg} |")
            lines.append("")

        if result.categories:
            lines.append("### Key Files")
            lines.append("")
            for cat, files in sorted(result.categories.items()):
                label = cat.replace("_", " ").title()
                files_str = ", ".join(f"`{f}`" for f in sorted(files))
                lines.append(f"- **{label}**: {files_str}")
            lines.append("")

        return "\n".join(lines)

    def _render_stats(self, result: StatsResult) -> str:
        lines = ["## Code Statistics", ""]
        lines.append(f"- **Total files**: {result.total_files}")
        lines.append(f"- **Total lines**: {result.total_lines:,}")
        lines.append(f"- **Total size**: {self._format_size(result.total_size)}")
        lines.append("")

        if result.by_language:
            table = [
                "### By Language",
                "",
                "| Language | Files | Lines | Size |",
                "|----------|-------|-------|------|",
            ]
            for lang, data in sorted(result.by_language.items(), key=lambda x: -x[1]["lines"]):
                lang_esc = self._escape_md_table(lang)
                table.append(f"| {lang_esc} | {data['files']} | {data['lines']:,} | {self._format_size(data['size'])} |")
            table.append("")
            lines.append(self._collapse(
                f"By Language ({len(result.by_language)} languages)",
                "\n".join(table),
            ))
            lines.append("")

        if result.largest_files:
            files_list = ["### Largest Files", ""]
            for path, lines_count in result.largest_files:
                files_list.append(f"- `{path}` — {lines_count:,} lines")
            files_list.append("")
            lines.append(self._collapse(
                f"Largest Files (top {len(result.largest_files)})",
                "\n".join(files_list),
            ))
            lines.append("")

        return "\n".join(lines)

    def _render_dependencies(self, result: DependenciesResult) -> str:
        lines = ["## Dependencies", ""]

        for ecosystem, data in [
            ("Python", result.python),
            ("JavaScript/TypeScript", result.javascript),
            ("Go", result.go),
            ("Rust", result.rust),
        ]:
            if not data:
                continue
            eco_lines = [f"### {ecosystem}"]
            for file, deps in data.items():
                eco_lines.append(f"**{file}**")
                if isinstance(deps, dict):
                    for key, val in deps.items():
                        if isinstance(val, dict):
                            eco_lines.append(f"  - {key}: {len(val)} packages")
                        elif isinstance(val, list):
                            eco_lines.append(f"  - {key}: {len(val)} entries")
                        else:
                            eco_lines.append(f"  - {key}: {val}")
                else:
                    eco_lines.append(f"  - {deps}")
            eco_lines.append("")
            lines.append(self._collapse(
                f"{ecosystem} ({len(data)} files)",
                "\n".join(eco_lines),
            ))
            lines.append("")

        return "\n".join(lines)

    def _render_git(self, result: GitResult) -> str:
        lines = ["## Git Information", ""]
        lines.append(f"- **Current branch**: {result.current_branch}")
        if result.remote_url:
            lines.append(f"- **Remote**: {result.remote_url}")
        lines.append("")

        if result.recent_commits:
            lines.append("### Recent Commits")
            lines.append("")
            lines.append("| Hash | Author | Date | Message |")
            lines.append("|------|--------|------|---------|")
            for c in result.recent_commits:
                msg = self._escape_md_table(c['message'][:60])
                lines.append(f"| {c['hash']} | {c['author']} | {c['date']} | {msg}... |")
            lines.append("")

        if result.branches:
            branches_lines = ["### Branches", ""]
            limit = 30
            for b in result.branches[:limit]:
                branches_lines.append(f"- {b}")
            if len(result.branches) > limit:
                branches_lines.append(f"- *...and {len(result.branches) - limit} more*")
            branches_lines.append("")
            lines.append(self._collapse(
                f"Branches ({len(result.branches)})",
                "\n".join(branches_lines),
            ))
            lines.append("")

        if result.contributors:
            contrib_lines = ["### Top Contributors", ""]
            contrib_lines.append("| Contributor | Commits |")
            contrib_lines.append("|-------------|---------|")
            for c in result.contributors[:15]:
                contrib_lines.append(f"| {c['name']} | {c['commits']} |")
            contrib_lines.append("")
            lines.append(self._collapse(
                f"Top Contributors ({len(result.contributors)})",
                "\n".join(contrib_lines),
            ))
            lines.append("")

        return "\n".join(lines)

    def _render_architecture(self, result: ArchitectureResult) -> str:
        lines = ["## Architecture Overview", ""]

        if result.layers:
            layer_lines = ["### Detected Layers", ""]
            for layer, files in sorted(result.layers.items()):
                layer_lines.append(f"**{layer.title()}** ({len(files)} files)")
                for f in sorted(files)[:10]:
                    layer_lines.append(f"  - `{f}`")
                if len(files) > 10:
                    layer_lines.append(f"  - *...and {len(files) - 10} more*")
                layer_lines.append("")
            lines.append(self._collapse(
                f"Detected Layers ({len(result.layers)})",
                "\n".join(layer_lines),
            ))
            lines.append("")

        if result.entry_points:
            lines.append("### Entry Points")
            lines.append("")
            for f in sorted(result.entry_points):
                lines.append(f"- `{f}`")
            lines.append("")

        if result.import_graph:
            import_count = sum(len(v) for v in result.import_graph.values())
            lines.append("### Module Dependencies")
            lines.append("")
            m_label = "module" if len(result.import_graph) == 1 else "modules"
            v_label = "other module" if import_count == 1 else "other modules"
            v_verb = "imports" if len(result.import_graph) == 1 else "import"
            lines.append(f"- **{len(result.import_graph)}** {m_label} {v_verb} **{import_count}** {v_label}")
            if result.circular_deps:
                lines.append(f"- **{len(result.circular_deps)}** circular dependenc{'y' if len(result.circular_deps) == 1 else 'ies'} detected")
                for cycle in result.circular_deps:
                    arrow_chain = " → ".join(cycle)
                    lines.append(f"  - `{arrow_chain}`")
            lines.append("")

            import_items = []
            for file_path, imports in sorted(result.import_graph.items()):
                import_items.append(f"- `{file_path}` → {', '.join(imports[:8])}{', ...' if len(imports) > 8 else ''}")
            lines.append(self._collapse(
                f"Import Graph ({len(result.import_graph)} files)",
                "\n".join(import_items),
            ))
            lines.append("")

        return "\n".join(lines)

    def _render_security(self, result: SecurityResult) -> str:
        lines = ["## Security Notes", ""]

        if result.env_files:
            lines.append("### Environment Files Found")
            lines.append("")
            for f in result.env_files:
                lines.append(f"- `{f}` ⚠️")
            lines.append("")

        if result.findings:
            findings_lines = ["### Potential Secrets Detected", ""]
            findings_lines.append("| File | Type | Line | Preview |")
            findings_lines.append("|------|------|------|---------|")
            for f in result.findings[:30]:
                file_esc = self._escape_md_table(f['file'])
                preview_esc = self._escape_md_table(f['preview'])
                findings_lines.append(f"| `{file_esc}` | {f['type']} | {f['line']} | `{preview_esc}` |")
            if len(result.findings) > 30:
                findings_lines.append(f"| *...and {len(result.findings) - 30} more* | | | |")
            findings_lines.append("")
            lines.append(f"<details open>\n<summary>Potential Secrets ({len(result.findings)} detected)</summary>\n\n" + "\n".join(findings_lines) + "\n</details>")
            lines.append("")

        if result.high_entropy_strings:
            entropy_lines = ["### High Entropy Strings (Review Recommended)", ""]
            entropy_lines.append("| File | Entropy | Line | Preview |")
            entropy_lines.append("|------|---------|------|---------|")
            for f in result.high_entropy_strings[:20]:
                file_esc = self._escape_md_table(f['file'])
                preview_esc = self._escape_md_table(f['preview'])
                entropy_lines.append(f"| `{file_esc}` | {f['entropy']} | {f['line']} | `{preview_esc}` |")
            entropy_lines.append("")
            lines.append(f"<details>\n<summary>High Entropy Strings ({len(result.high_entropy_strings)} found, review recommended)</summary>\n\n" + "\n".join(entropy_lines) + "\n</details>")
            lines.append("")

        return "\n".join(lines)

    def _render_todos(self, result: TodosResult) -> str:
        lines = ["## TODO / FIXME / HACK", ""]
        if not result.items:
            lines.append("No developer comments found.")
            return "\n".join(lines)

        tag_order = ["FIXME", "HACK", "TODO", "XXX", "BUG", "WORKAROUND", "HACKME"]
        for tag in tag_order:
            tag_items = [i for i in result.items if i["tag"] == tag]
            if not tag_items:
                continue
            total = result.count_by_tag.get(tag, 0)
            lines.append(f"### {tag} ({total} total)")

            if total > len(tag_items):
                lines.append(f"*Showing top {len(tag_items)} of {total}*")

            lines.append("")
            lines.append("| File | Line | Message |")
            lines.append("|------|------|---------|")
            for item in tag_items:
                msg = self._escape_md_table(item["message"]) if item["message"] else "—"
                lines.append(f"| `{item['file']}` | {item['line']} | {msg} |")
            lines.append("")
        return "\n".join(lines)

    def _render_scripts(self, result: ScriptsResult) -> str:
        lines = ["## Build Scripts", ""]
        has_any = False

        if result.package_json:
            has_any = True
            lines.append("### package.json Scripts")
            lines.append("")
            for name, cmd in sorted(result.package_json.items()):
                lines.append(f"- **{name}**: `{cmd}`")
            lines.append("")

        if result.makefile_targets:
            has_any = True
            lines.append("### Makefile Targets")
            lines.append("")
            for t in result.makefile_targets[:30]:
                lines.append(f"- `{t}`")
            if len(result.makefile_targets) > 30:
                lines.append(f"- *...and {len(result.makefile_targets) - 30} more*")
            lines.append("")

        if result.justfile_recipes:
            has_any = True
            lines.append("### Justfile Recipes")
            lines.append("")
            for r in result.justfile_recipes[:30]:
                lines.append(f"- `{r}`")
            if len(result.justfile_recipes) > 30:
                lines.append(f"- *...and {len(result.justfile_recipes) - 30} more*")
            lines.append("")

        if result.pyproject_scripts:
            has_any = True
            lines.append("### pyproject.toml Scripts")
            lines.append("")
            for name, cmd in sorted(result.pyproject_scripts.items()):
                lines.append(f"- **{name}**: `{cmd}`")
            lines.append("")

        if not has_any:
            lines.append("No build scripts found.")

        return "\n".join(lines)

    def _render_env_vars(self, result: EnvVarsResult) -> str:
        lines = ["## Environment Variables", ""]
        if not result.variables:
            lines.append("No environment variable references found.")
            return "\n".join(lines)

        lines.append(f"**{len(result.variables)}** unique environment variables referenced.")
        lines.append("")
        lines.append("| Variable | Files |")
        lines.append("|----------|-------|")
        for var, files in list(result.variables.items())[:40]:
            files_esc = ", ".join(f"`{self._escape_md_table(str(f))}`" for f in files[:5])
            if len(files) > 5:
                files_esc += f", *...and {len(files) - 5} more*"
            var_esc = self._escape_md_table(var)
            lines.append(f"| `{var_esc}` | {files_esc} |")
        if len(result.variables) > 40:
            lines.append(f"| *...and {len(result.variables) - 40} more* | |")
        lines.append("")
        return "\n".join(lines)

    def _render_cicd(self, result: CicdResult) -> str:
        lines = ["## CI/CD Configuration", ""]
        has_any = False

        if result.github_actions:
            has_any = True
            lines.append("### GitHub Actions")
            for wf in result.github_actions:
                on = ", ".join(wf["on"]) if isinstance(wf["on"], list) else wf["on"]
                jobs = ", ".join(wf["jobs"][:8])
                if len(wf["jobs"]) > 8:
                    jobs += ", ..."
                lines.append(f"- **{wf['name']}** — on {on}")
                lines.append(f"  - Jobs: {jobs}")
            lines.append("")

        if result.gitlab_ci:
            has_any = True
            stages = set(j["stage"] for j in result.gitlab_ci)
            lines.append(f"### GitLab CI — Stages: {', '.join(sorted(stages))}")
            for job in result.gitlab_ci:
                img = f" ({job['image']})" if job["image"] else ""
                lines.append(f"- **{job['name']}** (stage: {job['stage']}){img}")
            lines.append("")

        if result.circleci:
            has_any = True
            lines.append("### CircleCI Jobs")
            for job in result.circleci:
                lines.append(f"- **{job['name']}** — {job['steps']} steps")
            lines.append("")

        if result.jenkins_stages:
            has_any = True
            lines.append("### Jenkins Pipeline Stages")
            for s in result.jenkins_stages:
                lines.append(f"- {s}")
            lines.append("")

        if not has_any:
            lines.append("No CI/CD configuration found.")
        return "\n".join(lines)

    def _render_database(self, result: DatabaseResult) -> str:
        lines = ["## Database Schema", ""]
        has_any = False

        if result.orm_types:
            has_any = True
            lines.append("### Detected ORM")
            for t in result.orm_types:
                lines.append(f"- **{t}**")
            lines.append("")

        if result.model_count:
            has_any = True
            lines.append(f"- **{result.model_count}** models across {len(result.model_files)} files")
            lines.append("")

        if result.migration_files:
            has_any = True
            lines.append(f"### Migration Files ({len(result.migration_files)})")
            for m in result.migration_files[:15]:
                lines.append(f"- `{m}`")
            if len(result.migration_files) > 15:
                lines.append(f"- *...and {len(result.migration_files) - 15} more*")
            lines.append("")

        if result.schema_files:
            has_any = True
            lines.append("### Schema Files")
            for s in result.schema_files:
                lines.append(f"- `{s}`")
            lines.append("")

        if result.model_files:
            has_any = True
            lines.append(f"### Model Files ({len(result.model_files)})")
            for m in result.model_files[:15]:
                lines.append(f"- `{m}`")
            if len(result.model_files) > 15:
                lines.append(f"- *...and {len(result.model_files) - 15} more*")
            lines.append("")

        if not has_any:
            lines.append("No database schema detected.")
        return "\n".join(lines)

    def _render_type_coverage(self, result: TypeCoverageResult) -> str:
        lines = ["## Type Coverage", ""]
        if result.typed_files == 0 and result.untyped_files == 0:
            lines.append("No typed or untyped files found.")
            return "\n".join(lines)

        total = result.typed_files + result.untyped_files
        pct = round(result.typed_files / total * 100, 1) if total else 0
        lines.append(f"- **{pct}%** of files are typed")
        lines.append(f"- {result.typed_files} typed files, {result.untyped_files} untyped files")
        lines.append(f"- {result.typed_lines:,} typed lines, {result.untyped_lines:,} untyped lines")
        lines.append("")

        if result.by_extension:
            lines.append("### By Extension")
            lines.append("")
            lines.append("| Extension | Files | Typed Lines | Untyped Lines |")
            lines.append("|-----------|-------|-------------|---------------|")
            for ext, data in sorted(result.by_extension.items()):
                ext_esc = self._escape_md_table(ext)
                lines.append(f"| {ext_esc} | {data['files']} | {data['typed_lines']:,} | {data['untyped_lines']:,} |")
            lines.append("")

        return "\n".join(lines)

    def _render_complexity(self, result: ComplexityResult) -> str:
        lines = ["## Code Complexity", ""]

        lines.append(f"- **Average function length**: {result.avg_function_length} lines")
        lines.append(f"- **Max nesting depth**: {result.max_nesting}")
        lines.append("")

        if result.complex_files:
            complex_table = ["| File | Long Functions | Max Nesting | Score |", "|------|---------------|-------------|-------|"]
            for entry in result.complex_files:
                n_long = len(entry["long_functions"])
                file_esc = self._escape_md_table(entry['file'])
                complex_table.append(f"| `{file_esc}` | {n_long} | {entry['max_nesting']} | {entry['score']} |")
            complex_table.append("")
            lines.append(self._collapse(
                f"Complex Files ({len(result.complex_files)})",
                "\n".join(complex_table),
            ))
            lines.append("")
        else:
            lines.append("No complex files detected.")

        return "\n".join(lines)

    def _render_duplicates(self, result: DuplicateResult) -> str:
        lines = ["## Duplicate Files", ""]

        if result.total_duplicates == 0:
            lines.append("No duplicate files found.")
            return "\n".join(lines)

        lines.append(f"- **{result.total_duplicates}** duplicate file(s) found")
        if result.total_saved_bytes:
            lines.append(f"- **{self._format_size(result.total_saved_bytes)}** could be saved")
        lines.append("")

        dup_table = ["| Duplicate File | Original | Size | Similarity |", "|----------------|----------|------|------------|"]
        limit = 20
        for dup in result.duplicates[:limit]:
            sim = f"{dup['similarity']*100:.0f}%"
            file_esc = self._escape_md_table(dup['file'])
            dup_of_esc = self._escape_md_table(dup['duplicate_of'])
            dup_table.append(f"| `{file_esc}` | `{dup_of_esc}` | {self._format_size(dup['size'])} | {sim} |")
        if len(result.duplicates) > limit:
            dup_table.append(f"| *...and {len(result.duplicates) - limit} more* | | | |")
        dup_table.append("")
        lines.append(self._collapse(
            f"Duplicate Files ({len(result.duplicates)} found)",
            "\n".join(dup_table),
        ))
        lines.append("")

        return "\n".join(lines)

    def _render_api_endpoints(self, result: ApiEndpointResult) -> str:
        lines = ["## API Endpoints", ""]
        if not result.endpoints:
            lines.append("No API endpoints detected.")
            return "\n".join(lines)

        by_framework: dict[str, list[dict]] = {}
        for ep in result.endpoints:
            by_framework.setdefault(ep["framework"], []).append(ep)

        for framework in ["FastAPI", "Flask", "Django", "Express", "Rails"]:
            fw_eps = by_framework.get(framework)
            if not fw_eps:
                continue
            lines.append(f"### {framework} ({len(fw_eps)} endpoints)")
            lines.append("")
            lines.append("| Method | Path | File | Line |")
            lines.append("|--------|------|------|------|")
            for ep in sorted(fw_eps, key=lambda x: (x["path"], x["method"])):
                path_esc = self._escape_md_table(ep['path'])
                file_esc = self._escape_md_table(ep['file'])
                lines.append(f"| {ep['method']} | `{path_esc}` | `{file_esc}` | {ep['line']} |")
            lines.append("")
        return "\n".join(lines)

    def _format_size(self, size: int) -> str:
        for unit in ["B", "KB", "MB", "GB"]:
            if size < 1024:
                return f"{size:.1f} {unit}"
            size /= 1024
        return f"{size:.1f} TB"
