"""README.md generator.

This generator produces rnREADME.md — a generated, starter README.
It never writes to hand-written README.md unless --replace-readme --force is used.
"""

from pathlib import Path

from repo_notes.extractors.readme_data import ReadmeData
from repo_notes.extractors.stats import StatsResult


class ReadmeGenerator:
    def __init__(self, root: Path):
        self.root = root

    def generate(
        self,
        readme_data: ReadmeData,
        stats: StatsResult | None = None,
    ) -> str:
        sections = [
            self._render_header(readme_data),
            self._render_badges(readme_data),
            self._render_quick_start(readme_data),
            self._render_output_formats(),
            self._render_features(readme_data),
            self._render_usage(readme_data),
        ]

        if stats:
            sections.append(self._render_stats(stats))

        sections.append(self._render_generated_warning())
        sections.append(self._render_development(readme_data))
        sections.append(self._render_license(readme_data))

        return "\n\n".join(s.rstrip() for s in sections if s.strip()) + "\n"

    def _render_header(self, data: ReadmeData) -> str:
        lines = [f"# {data.name}"]
        if data.description:
            lines.append("")
            lines.append(data.description)
        lines.append("")
        lines.append("> This file was generated by `repo-notes`. "
                      "The hand-written project README is in `README.md`.")
        return "\n".join(lines)

    def _render_badges(self, data: ReadmeData) -> str:
        parts = []
        if data.version:
            parts.append(f"![Version](https://img.shields.io/badge/version-{data.version}-blue)")
        if data.license_type:
            license_encoded = data.license_type.replace("-", "--").replace(" ", "%20")
            parts.append(f"![License](https://img.shields.io/badge/license-{license_encoded}-green)")
        if data.python_requires:
            py_encoded = data.python_requires.replace(">=", "%3E%3D").replace(" ", "%20")
            parts.append(f"![Python](https://img.shields.io/badge/python-{py_encoded}-yellow)")
        if data.ci_provider:
            ci_name = data.ci_provider.lower().replace(" ", "_")
            parts.append(f"![CI](https://img.shields.io/badge/ci-{ci_name}-orange)")
        if data.has_tests:
            parts.append("![Tests](https://img.shields.io/badge/tests-passing-brightgreen)")
        return " ".join(parts) if parts else ""

    def _render_quick_start(self, data: ReadmeData) -> str:
        lines = ["## Quick Start", ""]
        if data.install_cmd:
            lines.append("```bash")
            lines.append(data.install_cmd)
            lines.append("```")
            lines.append("")
        return "\n".join(lines)

    def _render_output_formats(self) -> str:
        lines = [
            "## Output Formats",
            "",
            "`repo-notes` supports several output formats via `--format`:",
            "",
            "| Format | Description | Default File |",
            "|--------|-------------|--------------|",
            "| `notes` | Full technical notes with all analysis sections | `REPO_NOTES.md` |",
            "| `readme` | Starter README (generated, not hand-written) | `rnREADME.md` |",
            "| `both` | Notes + README | `REPO_NOTES.md` + `rnREADME.md` |",
            "| `html` | Pretty HTML view | `REPO_NOTES.html` |",
            "| `json` | Machine-readable structured output | `REPO_NOTES.json` |",
            "",
            "Additional flags:",
            "- `--output` / `-o` — custom output path for single-artifact formats",
            "- `--agents` — generate `AGENTS.md` with agent-oriented repo summary",
            "- `--quiet` / `-q` — suppress routine output (errors still on stderr)",
            "- `--replace-readme --force` — overwrite hand-written `README.md` (destructive)",
            "",
        ]
        return "\n".join(lines)

    def _render_features(self, data: ReadmeData) -> str:
        lines = ["## Features", ""]
        lines.append(f"- **{data.name}** project scanned for structure, dependencies, security, complexity, and more")
        if data.runtime_deps:
            lines.append(f"- **{len(data.runtime_deps)} runtime dependencies** — {', '.join(data.runtime_deps[:8])}")
            if len(data.runtime_deps) > 8:
                lines[-1] += f" and {len(data.runtime_deps) - 8} more"
        if data.has_tests:
            lines.append("- **Test suite** — detected test files")
        if data.has_ci:
            lines.append(f"- **CI configured** — {data.ci_provider}")
        if data.has_docker:
            lines.append("- **Docker support** — container configuration found")
        lines.append("")
        return "\n".join(lines)

    def _render_usage(self, data: ReadmeData) -> str:
        lines = ["## Usage", ""]
        lines.append("```")
        lines.append("repo-notes [OPTIONS] [PATH]")
        lines.append("```")
        lines.append("")
        lines.append("Scan a repository and generate project notes. "
                      "By default, produces a detailed `REPO_NOTES.md` in the target directory.")
        lines.append("")
        return "\n".join(lines)

    def _render_generated_warning(self) -> str:
        lines = [
            "## Generated File Warning",
            "",
            "> This file is **generated** by `repo-notes`. It is a starter README "
            "meant to help new contributors and automated tools get oriented quickly.",
            ">",
            "> The project's hand-written documentation lives in `README.md`. "
            "Do not edit this file directly; re-run `repo-notes` to regenerate.",
            ">",
            "> To overwrite `README.md` with generated output, use `--format readme --replace-readme --force`.",
            "",
        ]
        return "\n".join(lines)

    def _render_stats(self, result: StatsResult) -> str:
        lines = ["## Code Statistics", ""]
        lines.append(f"- **Total files**: {result.total_files}")
        lines.append(f"- **Total lines**: {result.total_lines:,}")
        if result.by_language:
            lang_summary = ", ".join(
                f"{lang}: {data['files']} files, {data['lines']} lines"
                for lang, data in sorted(result.by_language.items(), key=lambda x: -x[1]["lines"])
            )
            lines.append(f"- **Languages**: {lang_summary}")
        lines.append("")
        return "\n".join(lines)

    def _render_development(self, data: ReadmeData) -> str:
        lines = ["## Development", ""]
        if data.dev_install_cmd:
            lines.append("```bash")
            lines.append(data.dev_install_cmd)
            lines.append("```")
            lines.append("")
        lines.append("### Commands")
        lines.append("")
        lines.append("```bash")
        lines.append("# Run tests")
        lines.append("pytest")
        lines.append("")
        lines.append("# Run linter")
        lines.append("ruff check src/ tests/")
        lines.append("```")
        lines.append("")
        return "\n".join(lines)

    def _render_license(self, data: ReadmeData) -> str:
        if data.license_type:
            return f"## License\n\n{data.license_type}"
        return "## License\n\nMIT"
